### ISSUE TITLE
menu is / can not be displayed after installation using the KingChaos package

### ISSUE THREAD

**Issue by b4l** [semiautomaticgit/SemiAutomaticClassificationPlugin#35]

**Comment by semiautomaticgit** [comment]
Thank you for reporting this. Unfortunately I think it is related to missing dependencies that should be solved in the KingChaos package.
Please report If you get any error message.

**Comment by b4l** [comment]
Unfortunately i don't get any error message in qgis. installed scipy and numpy and reinstalled the plugin - it still does not show up.

**Comment by b4l** [comment]
Ok, initiated to follow up on your proposal. Thank you!
